# New ports collection makefile for:	sslstrip
# Date created:		2009-04-17
# Whom:			User & <dragon@njord.localdomain>
#
# $FreeBSD$
#

PORTNAME=	sslstrip
PORTVERSION=	0.2
CATEGORIES=	security
MASTER_SITES= http://www.thoughtcrime.org/software/sslstrip/
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	${PORTNAME}-${PORTVERSION}
#EXTRACT_SUFX=

MAINTAINER=	kitchetech@gmail.com
COMMENT=	Python module for sslstrip

USE_PYTHON=     yes
USE_PYDISTUTILS=yes
PYDISTUTILS_PKGNAME=    pysslstrip

.include <bsd.port.mk>
